"useClient";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";


// import Shery from "sheryjs";

const inter = Inter({ subsets: ["latin"] });
// Shery.mouseFollower({
//   skew: true,
//   ease: "cubic-bezier(0.23, 1, 0.320, 1)",
//   duration: 1,
// });



export const metadata = {
  title: "Holmes-PG Accomodation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Navbar/>
           
        {children}
        
        <Footer/>
        
        </body>
    </html>
  );
}
